### ISSUE TITLE
Crash at world creation screen (1.20.1-1.3.1.0)

### ISSUE THREAD

**Issue by DESTINATIONTIME** [ACCBDD/dimensional_ascension_tetra_compat#4]
Game immediately crashed when clicking the "Create World" button, or "Single Player" button when no world is present. Is very re-producable with only the mod dependencies on the mod list (Tetra, Blue Skies and their libraries). 

[crash-2024-02-03_18.33.58-client.txt](https://github.com/ACCBDD/dimensional_ascension_tetra_compat/files/14151212/crash-2024-02-03_18.33.58-client.txt)

**Comment by killer2gudpl** [comment]
Same issue. Version of the mod - 1.3.1.2

Fixed it by going into winrar -> open the jar -> data/tetra/replacements/material and open spears.json in notepad++.

Remove bits from line 71 to 62 (cherry spear) and dont forget to remove "," from the (now) last entry. Otherwise its still going to crash.

Hope that helps.

Enjoy!

**Comment by ACCBDD** [comment]
Thank you both for reporting (and solving!) this issue! An update has been pushed and should resolve this issue.
